### ISSUE TITLE
Some multiline options don't work in bash

### ISSUE THREAD

**Issue by rottencandy** [roosta/fif#2]
Hi, thank you for this wonderful tool, fif fits my needs almost perfectly, and I love how snappy it is.

The default env vars for specifying multi line command args do not work in bash, since the `VAR=(...)` syntax doesn't work with multiline values.

An alternative would be to use quotes, like `VAR="..."`, since this works well with both zsh and bash.

**Comment by roosta** [comment]
Hello, thanks for opening an issue! Glad you found fif useful. Thanks for the heads up on this. I'll fix it as soon as I'm able.

**Comment by roosta** [comment]
I might need a bit of clarification here, I don't seem to have any issue running fif in bash...is it due to arguments taking this form? `--color always`, would changing it to `--color=always` work?

The reason I use array expansion for the optional arguments is that I can't seem to find a way to merge whatever is stored in the variable if it is a string, with the rest of the command arguments.

**Comment by rottencandy** [comment]
When I create miltiline vars using this form, only the first line gets saved:
```bash
$ export FIF_RG_OPTS=(
  --hidden
  --color always
  --colors 'match:none'
  --colors 'path:fg:blue'
  --colors 'line:fg:yellow'
)

$ echo $FIF_RG_OPTS
--hidden
```
Not sure if it's just my system, I'll test this on another device when I get a chance.

I assume combining vars would work fine with quotes too, like so:
```bash
$ export NEW_OPTS="
$EXISTING_OPTS
...
"

**Comment by roosta** [comment]
Same problem here, I understand the issue now, thanks :) I'll look into possible solutions, I've only ever tested setting options in zsh, which was an oversight.

**Comment by roosta** [comment]
turns out bash simply doesn't allow exporting arrays, so I had to find another solution. I've changed how you export args:
```bash
  export FIF_RG_OPTS="--hidden \
    --color always \
    --colors=match:none \
    --colors=path:fg:blue \
    --colors=line:fg:yellow \
    --follow"
# or this
  export FIF_RG_OPTS="--hidden --color always --colors=match:none --colors=path:fg:blue --colors=line:fg:yellow --follow"
```
Gotta be careful with the `newline` chars, it'll trip up fif if the backslash isn't included. Not perfect but I hope it can work.

Wanna try it out? its in branch [fix2](https://github.com/roosta/fif/tree/fix2)

**Comment by rottencandy** [comment]
Thanks for the super quick fix! I tried it out and it works great with bash.

**Comment by roosta** [comment]
Great :) thanks for the issue, glad I could resolve this.
